# Generated by Django 3.0.6 on 2020-05-24 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_turn_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Game'),
            preserve_default=False,
        ),
    ]
