# Generated by Django 3.0.6 on 2020-05-25 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200525_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turn',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='app.Game'),
        ),
    ]
