# Generated by Django 3.0.6 on 2020-07-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200525_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(default='chess', max_length=20),
            preserve_default=False,
        ),
    ]
